### ISSUE TITLE
Module.Network.FlowFormer missing

### ISSUE THREAD

**Issue by rometaidla** [castacks/MAC-VO#1]
Seems like `Module.Network.FlowFormer` is missing from the repository. For example when running:

```bash
python MACVO.py --odom ./Config/Experiment/MACVO/MACVO.yaml --data ./Config/Sequence/TartanAir_abandonfac_001.yaml
```

I get following error:
```bash
Traceback (most recent call last):
  File "projects/MAC-VO/MACVO.py", line 122, in <module>
    system = MACVO.from_config(asNamespace(exp_space.config), sequence)
  File "projects/MAC-VO/Odometry/MACVO.py", line 67, in from_config
    Frontend            = Module.IFrontend.instantiate(odomcfg.frontend.type, odomcfg.frontend.args)
  File "projects/MAC-VO/Utility/Extensions/SubclassRegistry.py", line 34, in instantiate
    else: return cls.__HIERARCHY[name2](*args, **kwargs)
  File "projects/MAC-VO/Module/Frontend/Frontend.py", line 58, in __init__
    self.context: T_Context       = self.init_context()
  File "projects/MAC-VO/Module/Frontend/Frontend.py", line 175, in init_context
    from ..Network.FlowFormer.configs.submission import get_cfg
ModuleNotFoundError: No module named 'Module.Network.FlowFormer'
```

Did I miss something in installation instructions or how to fix this problem?

**Comment by rometaidla** [comment]
Correct repository is here:
https://github.com/MAC-VO/MAC-VO
